### ISSUE TITLE
Проблема с оптимизацией

### ISSUE THREAD

**Issue by ilyasidorchik** [rusaksenov/homework-react-search#1]
Добавь `console.log('render')` здесь:
https://github.com/rusaksenov/homework-react-search/blob/8288efcff537657a95d1cb912295a9a64f0d8e7e/src/components/Search/Search.js#L6

Напиши что-нибудь в поисковое поле. Что будет в консоли?

**Comment by rusaksenov** [comment]
Предыдущее значение.

**Comment by akseonowww** [comment]
Предыдущее значение 
![image](https://user-images.githubusercontent.com/54501083/93019782-d6e4ff80-f5e1-11ea-9368-e6dc19aaf439.png)

**Comment by ilyasidorchik** [comment]
Да, то есть `render` логируется каждый перерендер компонента. То же самое с функцией-обработчиком ввода: она создаётся каждый раз. Это не дело.

Как можно оптимизировать?

**Comment by akseonowww** [comment]
Вынести функцию-обработчика ввода из компонента?
Функция-обработчика -- это: ?
```
const onInput = (e) => {
        setValue(e.target.value)
        console.log(value)
        console.log('___')
    }
```

**Comment by ilyasidorchik** [comment]
Нет.

**Comment by ilyasidorchik** [comment]
Нужно применить специальный хук. Найди его [в документации](https://ru.reactjs.org/docs/hooks-reference.html).

**Comment by akseonowww** [comment]
```
setState?

**Comment by ilyasidorchik** [comment]
Нет. `setState` не хук, хук — `useState`. Но не он нужен для оптимизации.

**Comment by akseonowww** [comment]
Может? 
```
useCallback

**Comment by ilyasidorchik** [comment]
Да.

**Comment by akseonowww** [comment]
Переписать нужно так? 
```
const onInput = useCallback(
    (e) => {
        setValue(e.target.value)
        console.log(value)
    }
)

**Comment by ilyasidorchik** [comment]
Да, но ещё добавить вторым аргументов хука список зависимостей, чтобы хук не срабатывал каждый рендер.
```
const onInput = useCallback(
    (e) => {
        setValue(e.target.value)
    },
    []
) 
```

**Comment by akseonowww** [comment]
Мне кажется так не должно быть, верно?
![image](https://user-images.githubusercontent.com/54501083/93227078-adaca680-f77c-11ea-8136-3289663fa3cf.png)
