### ISSUE TITLE
Кнопка отправки

### ISSUE THREAD

**Issue by ilyasidorchik** [rusaksenov/homework-react-search#2]
Я как пользователь хочу кнопку. Добавь её, пожалуйста.

Пока по клику на кнопку достаточно логировать значение поле. Потом ты будешь передавать его бэкенду. Не забудь про оптимизацию.

Стили всё ещё не нужны.

**Comment by ilyasidorchik** [comment]
Где оптимизация?

https://github.com/rusaksenov/homework-react-search/blob/5bdd9142e74a08e472e75aafaae9b086b2fa7b45/src/components/Search/Search.js#L13

**Comment by akseonowww** [comment]
```
const handleClick = useCallback(
        () => {
            console.log(value)
        },
        []
)

Вот так?

**Comment by ilyasidorchik** [comment]
Хук верный, но что логируется?

**Comment by akseonowww** [comment]
Данные инпута, value
