### ISSUE TITLE
Поиск доступных предметов на Решу ЕГЭ

### ISSUE THREAD

**Issue by ilyasidorchik** [rusaksenov/homework-react-search#3]
Пришла воображаемая 11-классница Даша и сказала, что не знает, есть ли нужный предмет на сайте «Решу ЕГЭ. Давай поможем Даше! ;-)

---

Даша будет писать запрос в поисковое поле и нажимать кнопку. Например, Даша напишет: «матема». Приложение должно вывести ответ уведомлением (пока обычным `alert`).

Для поиска тебе, фронтендеру, бэкендер сделал АПИ. Пример GET-запроса ниже. Дашина фраза передаётся как значение параметра `query`.
https://sdamgia-homework-backend.herokuapp.com/api/search?query=матем

Пример ответа:
```json
{
    "subject": {
        "name": "math",
        "title": "Математика профильная"
    }
}
```

**Comment by akseonowww** [comment]
Не прочитав все главы ["Сетевые запросы"](https://learn.javascript.ru/network) не стоит решать?

**Comment by ilyasidorchik** [comment]
Стоит.

**Comment by akseonowww** [comment]
Я правильно думаю, что нужно сделать хвостик **https://sdamgia-homework-backend.herokuapp.com/api/search?query=** и в конце добавлять значение **value**

**Comment by ilyasidorchik** [comment]
Да. Но как это сделать лучше, чем `'...query' + value`?

**Comment by akseonowww** [comment]
```
`...query=${value}`

**Comment by ilyasidorchik** [comment]
Да. А как называется такой способ?

**Comment by akseonowww** [comment]
Хотел сказать контектенация, но и в первом случае она есть. А других вариантов пока у меня нет.(

**Comment by ilyasidorchik** [comment]
Шаблонные строки

**Comment by ilyasidorchik** [comment]
[Шаблонные строки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/template_strings)

**Comment by rusaksenov** [comment]
Так выдаёт старое значение, т.е. ввожу "123", а в консоле будет "...=12". Значит нужна новая функция?
```
    const handleChange = useCallback(
        (e) => {
            setValue(e.target.value);
            console.log(` https://sdamgia-homework-backend.herokuapp.com/api/search?query=${value}`)
        },
        [value]
    )
```

**Comment by ilyasidorchik** [comment]
Не. Попробуй в обработчике клика прологировать.

**Comment by akseonowww** [comment]
Да точно. Начал перечитавать дз и понял. А при клике значение нормальное, но как отправить запрос?

**Comment by ilyasidorchik** [comment]
> Не прочитав все главы ["Сетевые запросы"](https://learn.javascript.ru/network) не стоит решать?

Ответ в этом разделе в 1-й ссылке.

**Comment by akseonowww** [comment]
Варнинг пишит, что данные заблокированы, т.к. нет заголовка CORS.
![image](https://user-images.githubusercontent.com/54501083/93636214-32592800-f9fc-11ea-85c9-421cb43862ae.png)
![image](https://user-images.githubusercontent.com/54501083/93636238-400ead80-f9fc-11ea-8d62-9c4a13fea943.png)

**Comment by ilyasidorchik** [comment]
Верно. Дело в том, что ты делаешь запрос на другой сайт. По умолчанию это запрещено для безопасности.

Чтобы разрешить, бэкенд должен отправить в запросе специальный HTTP-заголовок.

Я показал эту ситуацию, чтобы ты понял, зачем изучать CORS.
